# Generated by Django 5.2 on 2025-04-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('Appliances', 'Appliances'), ('Baby', 'Baby'), ('Clothing', 'Clothing'), ('Computer & Electronics', 'Computer & Electronics'), ('Groceries', 'Groceries'), ('Garden & Partio', 'Garden & Partio'), ('Homeware', 'Homeware'), ('Homekeeping', 'Homekeeping'), ('Outdoor & Sports', 'Outdoor & Sports'), ('Office Supplies & Stationary', 'Office Supplies & Stationary'), ('TV, Audio & Media', 'TV, Audio & Media')], max_length=50)),
                ('subcategory', models.CharField(choices=[('Refrigerators & Freezers', 'Refrigerators & Freezers'), ('Microwaves', 'Microwaves'), ('Ovens & Stoves', 'Ovens & Stoves'), ('Dishwashers', 'Dishwashers'), ('Blenders & Juicers', 'Blenders & Juicers'), ('Toasters & Sandwich Makers', 'Toasters & Sandwich Makers'), ('Coffee Machines & Kettles', 'Coffee Machines & Kettles'), ('Food Processors', 'Food Processors'), ('Washing Machines', 'Washing Machines'), ('Tumble Dryers', 'Tumble Dryers'), ('Steam Irons & Garment Steamers', 'Steam Irons & Garment Steamers'), ('Air Conditioners', 'Air Conditioners'), ('Fans', 'Fans'), ('Heaters', 'Heaters'), ('Electric Blankets', 'Electric Blankets')], max_length=100)),
                ('stock', models.PositiveIntegerField()),
                ('image', models.ImageField(null=True, upload_to='product_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
