# Generated by Django 5.2 on 2025-04-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Appliances', 'appliances'), ('Baby', 'baby'), ('Clothing', 'Clothing'), ('Computer & Electronics', 'Computer & Electronics'), ('Groceries', 'Groceries'), ('Garden & Partio', 'garden & partio'), ('Homeware', 'homeware'), ('Homekeeping', 'homekeeping'), ('Outdoor & Sports', 'outdoor & sports'), ('Office Supplies & Stationary', 'office & stationary'), ('TV, Audio & Media', 'tv, audio & media')], max_length=50),
        ),
    ]
