# Generated by Django 5.2 on 2025-04-12 09:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Refrigerators & Freezers', 'Refrigerators & Freezers'), ('Microwaves', 'Microwaves'), ('Ovens & Stoves', 'Ovens & Stoves'), ('Dishwashers', 'Dishwashers'), ('Blenders & Juicers', 'Blenders & Juicers'), ('Toasters & Sandwich Makers', 'Toasters & Sandwich Makers'), ('Coffee Machines & Kettles', 'Coffee Machines & Kettles'), ('Food Processors', 'Food Processors'), ('Washing Machines', 'Washing Machines'), ('Tumble Dryers', 'Tumble Dryers'), ('Steam Irons & Garment Steamers', 'Steam Irons & Garment Steamers'), ('Air Conditioners', 'Air Conditioners'), ('Fans', 'Fans'), ('Heaters', 'Heaters'), ('Electric Blankets', 'Electric Blankets'), ('Cookware', 'Cookware'), ('Utensils & Cutlery', 'Utensils & Cutlery'), ('Dinnerware', 'Dinnerware'), ('Glassware', 'Glassware & Mugs'), ('Storage', 'Food Storage'), ('Appliances', 'Kitchen Appliances'), ('cushions', 'Cushions & Throws'), ('curtains', 'Curtains & Blinds'), ('rugs', 'Rugs & Carpets'), ('lighting', 'Lamps & Lighting'), ('tables', 'Coffee/Side Tables'), ('wallart', 'Wall Art & Frames'), ('bedding', 'Bedding'), ('mattresses', 'Mattresses'), ('wardrobes', 'Wardrobes & Drawers'), ('lamps', 'Bedside Lamps'), ('blankets', 'Blankets')], max_length=100),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pay.cart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pay.product')),
            ],
        ),
    ]
