# Generated by Django 5.2 on 2025-04-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0006_cartitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Appliances', 'Appliances'), ('Baby', 'Baby'), ('Computer & Electronics', 'Computer & Electronics'), ('Groceries', 'Groceries'), ('Homeware', 'Homeware'), ('TV, Audio & Media', 'TV, Audio & Media')], max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.CharField(choices=[('Refrigerators & Freezers', 'Refrigerators & Freezers'), ('Microwaves', 'Microwaves'), ('Ovens & Stoves', 'Ovens & Stoves'), ('Steam Irons & Garment Steamers', 'Steam Irons & Garment Steamers'), ('Air Conditioners', 'Air Conditioners'), ('Cookware', 'Cookware'), ('Dinnerware', 'Dinnerware'), ('Glassware', 'Glassware & Mugs'), ('curtains', 'Curtains & Blinds'), ('wallart', 'Wall Art & Frames'), ('Bedding', 'Bedding'), ('Wardrobes & Drawers', 'Wardrobes & Drawers'), ('Baby & Toddler Food', 'Baby & Toddler Food'), ('Baby Care', 'Baby Care'), ('Nappies & Wipes', 'Nappies & Wipes'), ('Baby Clothing', 'Baby Clothing'), ('Computers, Laptops & Tablets', 'Computers, Laptops & Tablets'), ('Accessories', 'Accessories'), ('Powerbanks', 'Powerbanks'), ('Mouse, Keyboards & Speakers', 'Mouse, Keyboards & Speakers'), ('Cables & Connectors', 'Cables & Connectors'), ('Fresh Produce', 'Fresh Produce'), ('Meet & Poultry', 'Meet & Poultry'), ('Bakery', 'Bakery'), ('Frozen Foods', 'Frozen Foods'), ('Snacks & Confectionery', 'Snacks & Confectionery'), ('Televisions', 'Televisions'), ('Soundbars & Speakers', 'Soundbars & Speakers'), ('Headphones & Earphones', 'Headphones & Earphones'), ('Media Players & Decoders', 'Media Players & Decoders'), ('TV Accessories', 'TV Accessories')], max_length=100),
        ),
    ]
