# Generated by Django 5.2 on 2025-04-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0011_transactionitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Mpesa', 'Mpesa'), ('EcoCash', 'EcoCash'), ('C-Pay', 'C-Pay'), ('PayPal', 'PayPal'), ('Crypto', 'Crypto')], max_length=30, null=True),
        ),
        migrations.DeleteModel(
            name='TransactionItem',
        ),
    ]
