# Generated by Django 5.2 on 2025-05-03 11:05

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pay', '0012_transaction_payment_method_delete_transactionitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonCart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='AnonTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('session_key', models.CharField(db_index=True, max_length=100)),
                ('cart_snapshot', models.JSONField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Mpesa', 'Mpesa'), ('EcoCash', 'EcoCash'), ('C-Pay', 'C-Pay'), ('PayPal', 'PayPal'), ('Crypto', 'Crypto')], max_length=30, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnonCartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Pay.anoncart')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pay.product')),
            ],
        ),
    ]
